name: custom_gallery_display
description: Customization of the gallery display or even camera and video.
version: 0.5.0
homepage: https://github.com/AhmedAbdoElhawary/custom_gallery_display.git

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  shimmer: ^2.0.0

  #image_crop: ^0.4.1 Temporary added to resolve the dependency causing issue
  #image_crop-0.4.1/lib/src/crop.dart:63:68:
  #Error: The class 'Drag' can't be used as a mixin because it isn't a mixin class nor a mixin.
  image_crop:
    git:
      url: https://github.com/tsafundzic/image_crop.git
  camera: ^0.10.0+1
  image: ^3.2.0
  video_player: ^2.4.5
  image_picker: ^0.8.5+3
  photo_manager: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
publish_to: none